import { useState } from 'react';
import { getTopics } from '../services/api';
import type { Topic } from '../types';
import './SummaryViewer.css';

interface SummaryViewerProps {
  moduleCode: string;
}

export default function SummaryViewer({ moduleCode }: SummaryViewerProps) {
  const [topics, setTopics] = useState<Topic[]>([]);
  const [selectedTopic, setSelectedTopic] = useState<Topic | null>(null);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [summary, setSummary] = useState<{
    topic_name: string;
    summary: string;
    key_points: string[];
    sources: any[];
  } | null>(null);

  const loadTopics = async () => {
    if (!moduleCode) return;

    setLoading(true);
    try {
      const data = await getTopics(moduleCode);
      setTopics(data);
    } catch (error) {
      console.error('Failed to load topics:', error);
    } finally {
      setLoading(false);
    }
  };

  useState(() => {
    if (moduleCode) {
      loadTopics();
    }
  });

  const generateSummary = async (topic: Topic) => {
    setSelectedTopic(topic);
    setGenerating(true);
    setSummary(null);

    try {
      const response = await fetch(`http://localhost:8000/api/query/summary?topic_id=${topic.id}&module_code=${moduleCode}`, {
        method: 'POST'
      });

      if (response.ok) {
        const data = await response.json();
        setSummary(data);
      } else {
        throw new Error('Failed to generate summary');
      }
    } catch (error) {
      console.error('Error generating summary:', error);
      // Fallback summary
      setSummary({
        topic_name: topic.name,
        summary: topic.description || 'Summary generation requires LLM provider to be configured.',
        key_points: [],
        sources: topic.appearances || []
      });
    } finally {
      setGenerating(false);
    }
  };

  const exportAsMarkdown = () => {
    if (!summary) return;

    const markdown = `# ${summary.topic_name}

## Summary
${summary.summary}

## Key Points
${summary.key_points.map(point => `- ${point}`).join('\n')}

## Sources
${summary.sources.map(source => `- ${source.lecture_title} (Week ${source.week_number})`).join('\n')}

---
*Generated by Smart Lecture Assistant*
*Module: ${moduleCode}*
*Date: ${new Date().toLocaleDateString()}*
`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${summary.topic_name.replace(/\s+/g, '_')}_summary.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportAsPDF = () => {
    // Simple print-based PDF export
    if (!summary) return;

    const printContent = `
      <html>
        <head>
          <title>${summary.topic_name} - Summary</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; line-height: 1.6; }
            h1 { color: #646cff; }
            h2 { color: #333; margin-top: 24px; }
            ul { margin: 16px 0; }
            li { margin: 8px 0; }
            .footer { margin-top: 40px; color: #666; font-size: 12px; border-top: 1px solid #eee; padding-top: 20px; }
          </style>
        </head>
        <body>
          <h1>${summary.topic_name}</h1>
          <h2>Summary</h2>
          <p>${summary.summary}</p>
          ${summary.key_points.length > 0 ? `
            <h2>Key Points</h2>
            <ul>
              ${summary.key_points.map(point => `<li>${point}</li>`).join('')}
            </ul>
          ` : ''}
          <h2>Sources</h2>
          <ul>
            ${summary.sources.map(source => `<li>${source.lecture_title || 'Lecture'} (Week ${source.week_number})</li>`).join('')}
          </ul>
          <div class="footer">
            <p>Generated by Smart Lecture Assistant</p>
            <p>Module: ${moduleCode} | Date: ${new Date().toLocaleDateString()}</p>
          </div>
        </body>
      </html>
    `;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.print();
    }
  };

  if (!moduleCode) {
    return (
      <div className="summary-empty">
        <p>Select a module to view summaries</p>
      </div>
    );
  }

  return (
    <div className="summary-container">
      <div className="summary-sidebar">
        <h3>Topics</h3>
        <p className="sidebar-hint">Click a topic to generate summary</p>

        {loading ? (
          <div className="loading-spinner small"></div>
        ) : topics.length === 0 ? (
          <p className="no-topics">No topics detected yet</p>
        ) : (
          <ul className="topic-list">
            {topics.map(topic => (
              <li
                key={topic.id}
                className={`topic-item ${selectedTopic?.id === topic.id ? 'selected' : ''}`}
                onClick={() => generateSummary(topic)}
              >
                <span className="topic-name">{topic.name}</span>
                <span className="topic-count">
                  {topic.appearances?.length || 0} lectures
                </span>
              </li>
            ))}
          </ul>
        )}
      </div>

      <div className="summary-main">
        {!selectedTopic ? (
          <div className="summary-placeholder">
            <span className="placeholder-icon">📝</span>
            <p>Select a topic from the sidebar to generate its summary</p>
          </div>
        ) : generating ? (
          <div className="summary-generating">
            <div className="loading-spinner"></div>
            <p>Generating summary for "{selectedTopic.name}"...</p>
          </div>
        ) : summary ? (
          <div className="summary-content">
            <div className="summary-header">
              <h2>{summary.topic_name}</h2>
              <div className="export-buttons">
                <button onClick={exportAsMarkdown} className="export-btn">
                  📄 Export Markdown
                </button>
                <button onClick={exportAsPDF} className="export-btn">
                  🖨️ Print / PDF
                </button>
              </div>
            </div>

            <div className="summary-section">
              <h3>Summary</h3>
              <p>{summary.summary}</p>
            </div>

            {summary.key_points && summary.key_points.length > 0 && (
              <div className="summary-section">
                <h3>Key Points</h3>
                <ul className="key-points">
                  {summary.key_points.map((point, idx) => (
                    <li key={idx}>{point}</li>
                  ))}
                </ul>
              </div>
            )}

            <div className="summary-section">
              <h3>Appears In</h3>
              <div className="source-list">
                {summary.sources.map((source, idx) => (
                  <div key={idx} className="source-card">
                    <span className="source-week">Week {source.week_number}</span>
                    <span className="source-title">{source.lecture_title || 'Lecture'}</span>
                    {source.frequency && (
                      <span className="source-freq">{source.frequency} mentions</span>
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
}
